/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/gameboard.glb -o src/components/Gameboard.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useRef } from "react";
import { GAMEBOARD_LENGTH, SCROLL_SPEED } from "../App";

export function Gameboard(props) {
  const { nodes, materials } = useGLTF("/models/gameboard.glb");
  const ref = useRef();

  useFrame((_, delta) => {
    ref.current.position.z -= SCROLL_SPEED * delta;
    if (ref.current.position.z < -2 * GAMEBOARD_LENGTH) {
      ref.current.position.z = GAMEBOARD_LENGTH;
    }
  });

  return (
    <group {...props} dispose={null} ref={ref}>
      <group
        position={[-6.564, 0, 2.846]}
        rotation={[0, 0.294, 0]}
        scale={0.672}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present001.geometry}
          material={materials["Material.001"]}
          position={[31.075, 0, -24.218]}
          rotation={[0, 0.007, 0]}
          scale={1.07}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present005.geometry}
          material={materials["Material.001"]}
          position={[19.575, 0, 13.355]}
          scale={1.314}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present006.geometry}
          material={materials["Material.001"]}
          position={[29.901, 0, -21.739]}
          rotation={[0, -0.45, 0]}
          scale={0.914}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present007.geometry}
          material={materials["Material.001"]}
          position={[18.452, 0, 16.133]}
          rotation={[0, 0.056, 0]}
          scale={0.836}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Present008.geometry}
          material={materials["Material.001"]}
          position={[18.953, 0, 10.164]}
          rotation={[0, 0.056, 0]}
          scale={0.836}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arch_gate.geometry}
        material={materials.HalloweenBits}
        position={[10.578, -0.161, 0.041]}
        rotation={[0, -1.146, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.arch_gate_left.geometry}
          material={materials.HalloweenBits}
          position={[1.5, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.arch_gate_right.geometry}
          material={materials.HalloweenBits}
          position={[-1.5, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench.geometry}
        material={materials.HalloweenBits}
        position={[11.232, 0, -8.993]}
        rotation={[0, -0.954, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bench_decorated.geometry}
        material={materials.HalloweenBits}
        position={[8.272, 0, 3.939]}
        rotation={[0, -0.583, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.post_lantern.geometry}
        material={materials.HalloweenBits}
        position={[-9.965, 0, -7.411]}
        rotation={[0, 1.222, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_lantern_lantern.geometry}
          material={materials.HalloweenBits}
          position={[0, 3, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.post_skull.geometry}
        material={materials.HalloweenBits}
        position={[12.005, 0, -12.215]}
        rotation={[0, -1.097, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_skull_skull.geometry}
          material={materials.HalloweenBits}
          position={[0, 3, 1]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_dead_large.geometry}
        material={materials.HalloweenBits}
        position={[-7.932, 0, -2.029]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_dead_large_decorated.geometry}
        material={materials.HalloweenBits}
        position={[-10.481, 0, 8.717]}
        rotation={[0, 0.507, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_dead_medium.geometry}
        material={materials.HalloweenBits}
        position={[11.437, 0, -6.858]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.arch.geometry}
        material={materials.HalloweenBits}
        position={[-10.443, -0.013, 2.02]}
        rotation={[0, 0.637, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bone_A.geometry}
        material={materials.HalloweenBits}
        position={[5.502, 0, -5.028]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bone_C.geometry}
        material={materials.HalloweenBits}
        position={[-6.419, 0, -2.814]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.candle.geometry}
        material={materials.HalloweenBits}
        position={[-10.049, 0, -3.39]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.candle_melted.geometry}
        material={materials.HalloweenBits}
        position={[7.968, 0, -2.814]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.candle_thin.geometry}
        material={materials.HalloweenBits}
        position={[8.221, 0, 1.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.coffin_decorated.geometry}
        material={materials.HalloweenBits}
        position={[13.9, 0, 10.416]}
        rotation={[0, -0.534, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar.geometry}
        material={materials.HalloweenBits}
        position={[13.769, 0, -10.457]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plaque.geometry}
        material={materials.HalloweenBits}
        position={[-5.937, 0, 10.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.shrine.geometry}
        material={materials.HalloweenBits}
        position={[13.578, 0, -18.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_orange_large.geometry}
        material={materials.HalloweenBits}
        position={[-9.925, 0, -22.603]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_orange_medium.geometry}
        material={materials.HalloweenBits}
        position={[12.048, 0, 4.581]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_orange_small.geometry}
        material={materials.HalloweenBits}
        position={[-12.567, 0, -4.111]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_yellow_large.geometry}
        material={materials.HalloweenBits}
        position={[-10.471, 0, 18.631]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_yellow_medium.geometry}
        material={materials.HalloweenBits}
        position={[-6.667, 0, -14.731]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_yellow_small.geometry}
        material={materials.HalloweenBits}
        position={[-9.415, 0, 5.523]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_orange_large001.geometry}
        material={materials.HalloweenBits}
        position={[10.238, 0, 18.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tree_pine_yellow_medium001.geometry}
        material={materials.HalloweenBits}
        position={[9.606, 0, -21.676]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plaque001.geometry}
        material={materials.HalloweenBits}
        position={[6.279, 0, 10.215]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.floor_dirt.geometry}
        material={materials.HalloweenBits}
        position={[-14.412, -0.251, 26.778]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plaque004.geometry}
        material={materials.HalloweenBits}
        position={[-5.805, 0, -6.23]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plaque005.geometry}
        material={materials.HalloweenBits}
        position={[6.128, 0, -6.327]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Present004.geometry}
        material={materials["Material.001"]}
        position={[-7.665, 0, -10.207]}
        rotation={[0, -0.51, 0]}
        scale={1.119}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Present003.geometry}
        material={materials["Material.001"]}
        position={[-5.198, 0, -10.131]}
        rotation={[0, -0.364, 0]}
        scale={0.709}
      />
    </group>
  );
}

useGLTF.preload("/models/gameboard.glb");
