/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/assets/models/airplane.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { Matrix4, Quaternion, Vector3 } from 'three';
import { updatePlaneAxis } from './controls';
import { myPlayer } from 'playroomkit';
import { useEffect, useState } from 'react';
import * as THREE from 'three';

const x = new Vector3(1, 0, 0);
const y = new Vector3(0, 1, 0);
const z = new Vector3(0, 0, 1);
export const planePosition = new Vector3(0, 3, 7);

const delayedRotMatrix = new Matrix4();
const delayedQuaternion = new Quaternion();

export function Airplane({ player, ...props }) {
  
  const [thisIsMyPlane, setThisIsMyPlane] = useState(false);
  const [myColorMaterial, setMyColorMaterial] = useState();
  useEffect(() => {
    const me = myPlayer();
    setThisIsMyPlane(player.id === me.id);
    const color = player.getProfile().color;
    if (color) {
      const material = new THREE.MeshStandardMaterial();
      material.color.setHex(color.hex);
      setMyColorMaterial(material);
    }
  }, [player]);
  // thanks to:
  // https://sketchfab.com/3d-models/vintage-toy-airplane-7de2ecbc0acb4b1886c3df3d196c366b
  const { nodes, materials } = useGLTF('assets/models/airplane.glb');
  const groupRef = useRef();
  const helixMeshRef = useRef();

  useFrame(({ camera }) => {
    

    helixMeshRef.current.rotation.z -= 1.0;

    if (thisIsMyPlane) {

    updatePlaneAxis(x, y, z, planePosition, camera);

    const rotMatrix = new Matrix4().makeBasis(x, y, z);

    const matrix = new Matrix4()
    .multiply(new Matrix4().makeTranslation(planePosition.x, planePosition.y, planePosition.z))
    .multiply(rotMatrix);

    groupRef.current.matrixAutoUpdate = false;
    groupRef.current.matrix.copy(matrix);
    groupRef.current.matrixWorldNeedsUpdate = true;


    var quaternionA = new Quaternion().copy(delayedQuaternion);

    // warning! setting the quaternion from the rotation matrix will cause
    // issues that resemble gimbal locks, instead, always use the quaternion notation
    // throughout the slerping phase
    // quaternionA.setFromRotationMatrix(delayedRotMatrix);

    var quaternionB = new Quaternion();
    quaternionB.setFromRotationMatrix(rotMatrix);

    var interpolationFactor = 0.175;
    var interpolatedQuaternion = new Quaternion().copy(quaternionA);
    interpolatedQuaternion.slerp(quaternionB, interpolationFactor);
    delayedQuaternion.copy(interpolatedQuaternion);

    delayedRotMatrix.identity();
    delayedRotMatrix.makeRotationFromQuaternion(delayedQuaternion);

        const cameraMatrix = new Matrix4()
        .multiply(new Matrix4().makeTranslation(planePosition.x, planePosition.y, planePosition.z))
        .multiply(delayedRotMatrix)
        .multiply(new Matrix4().makeRotationX(-0.2))
        .multiply(
          new Matrix4().makeTranslation(0, 0.015, 1.76)
        );

      camera.matrixAutoUpdate = false;
      camera.matrix.copy(cameraMatrix);
      camera.matrixWorldNeedsUpdate = true; 

      // send position and rotation to playroom
      const position = new Vector3();
      const quaternion = new Quaternion();
      groupRef.current.getWorldPosition(position);
      groupRef.current.getWorldQuaternion(quaternion);
      player.setState("position", position);
      player.setState("x", x);
      player.setState("y", y);
      player.setState("z", z);
    }
    else{
      // interpolate position and rotation from playroom
      
      
      const position = player.getState("position");
      const x = player.getState("x");
      const y = player.getState("y");
      const z = player.getState("z");
      if (position && x && y && z) {
        const rotMatrix = new Matrix4().makeBasis(x, y, z);
      const matrix = new Matrix4()
    .multiply(new Matrix4().makeTranslation(position.x, position.y, position.z))
    .multiply(rotMatrix);

    groupRef.current.matrixAutoUpdate = false;
    groupRef.current.matrix.copy(matrix);
    groupRef.current.matrixWorldNeedsUpdate = true;
      }
    }
  });

  return (
    <>
      <group ref={groupRef}>
        <group {...props} dispose={null} scale={0.01} rotation-y={Math.PI}>
          <mesh geometry={nodes.supports.geometry} material={materials['Material.004']} />
          <mesh geometry={nodes.chassis.geometry} material={myColorMaterial} />
          <mesh geometry={nodes.helix.geometry} material={materials['Material.005']} ref={helixMeshRef} />
        </group>
      </group>
    </>
  )
}

useGLTF.preload('assets/models/airplane.glb');
